server:
  port: 8081
  servlet:
    context-path: /auth

# mysql
spring:
  datasource:
    url: jdbc:mysql://39.105.160.247:3306/authentication?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: mysql
  redis:
      host: 39.105.160.247
      port: 6379
      password: 123456

logging:
  level:
    root: debug

mybatis:
  mapperLocations: classpath*:mapper/*.xml

#security:
#  oauth2:
#    resource:
#      filter-order: 3
jwt:
  key: 123